---
- name: install httpd
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - mod_ssl
    - httpd-devel
    - openldap-devel
    - expat-devel
  register: install_httpd

- debug: var=install_httpd

- name: running and enabled httpd
  service: name=httpd state=started enabled=yes
  register: httpd_status

- debug: var=httpd_status
