---
- name: Create user defined database
  mysql_db:
    name: "{{ item.name }}"
    login_unix_socket: "{{ item.socket }}"
    config_file: "{{ item.config }}"
    #login_user: root
    state: present
  with_items: "{{ mariadb_databases }}"
  register: create_databases
  tags:
    - mariadb
- debug: var=create_databases
